### PR TITLE
Made a couple of additions to blinkr.yml

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by LightGuard** [comment]
Could you please mention in those issues that we're currently ignoring them in the blinkr report, and before they're closed we need to remove the ignore from the blinkr report to make sure it's really fixed?

**Comment by Dantheman720** [comment]
Will do.

**Comment by LightGuard** [comment]
Let me know when that's done here and I'll merge

**Comment by Dantheman720** [comment]
Alrighty, should be good to go

**Pull request merged**
